import { type Product } from "@/types/product"

export const products: Product[] = [
  // ─── ETHNIC WEAR ───────────────────────────────────────────────
  {
    id: "eth-001",
    name: "Rajwada Silk Lehenga",
    price: 18500,
    originalPrice: 24000,
    category: "ethnic",
    subcategory: "lehenga",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Red", "Gold", "Maroon"],
    tags: ["bestseller", "trending"],
    description: "Luxurious pure silk lehenga with intricate zari embroidery. Inspired by Rajwada's royal heritage. Perfect for weddings and sangeet ceremonies.",
    fabric: "Pure Silk",
    occasion: "Wedding",
    inStock: true,
    rating: 4.9,
    reviewCount: 127,
    cssColor: "#8B1A1A",
    patternType: "embroidered",
  },
  {
    id: "eth-002",
    name: "Banarasi Silk Saree",
    price: 12800,
    originalPrice: 16000,
    category: "ethnic",
    subcategory: "saree",
    sizes: ["Free Size"],
    colors: ["Gold", "Green", "Pink"],
    tags: ["bestseller", "new"],
    description: "Authentic Banarasi silk saree with gold zari border. A timeless classic for festivals and special occasions.",
    fabric: "Banarasi Silk",
    occasion: "Festival",
    inStock: true,
    rating: 4.8,
    reviewCount: 89,
    cssColor: "#B8860B",
    patternType: "embroidered",
  },
  {
    id: "eth-003",
    name: "Anarkali Georgette Suit",
    price: 4200,
    originalPrice: 5500,
    category: "ethnic",
    subcategory: "suit",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Pink", "Green"],
    tags: ["trending", "sale"],
    description: "Flowing Anarkali with Georgette fabric and mirror work. Light and elegant for all day wear.",
    fabric: "Georgette",
    occasion: "Party",
    inStock: true,
    rating: 4.6,
    reviewCount: 203,
    cssColor: "#1A237E",
    patternType: "printed",
  },
  {
    id: "eth-004",
    name: "Chanderi Cotton Kurti",
    price: 1800,
    category: "ethnic",
    subcategory: "kurti",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Pink", "Yellow"],
    tags: ["new"],
    description: "Handloom Chanderi cotton kurti with block print. Breathable and stylish for daily wear.",
    fabric: "Chanderi Cotton",
    occasion: "Casual",
    inStock: true,
    rating: 4.5,
    reviewCount: 312,
    cssColor: "#F8F0E3",
    patternType: "printed",
  },
  {
    id: "eth-005",
    name: "Navratri Chaniya Choli",
    price: 3600,
    originalPrice: 4800,
    category: "ethnic",
    subcategory: "lehenga",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Red", "Green", "Blue", "Pink"],
    tags: ["trending", "sale"],
    description: "Vibrant mirror-work Chaniya Choli for Navratri and Garba. Full flare with 3-tier layering.",
    fabric: "Cotton Blend",
    occasion: "Festival",
    inStock: true,
    rating: 4.7,
    reviewCount: 445,
    cssColor: "#E53935",
    patternType: "sequined",
  },
  {
    id: "eth-006",
    name: "Khadi Salwar Kameez",
    price: 2200,
    category: "ethnic",
    subcategory: "suit",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Beige", "Grey"],
    tags: ["new"],
    description: "Handspun Khadi salwar kameez with subtle embroidery. Sustainable and elegant.",
    fabric: "Khadi",
    occasion: "Casual",
    inStock: true,
    rating: 4.4,
    reviewCount: 78,
    cssColor: "#F5F0E8",
    patternType: "solid",
  },
  {
    id: "eth-007",
    name: "Madhubani Printed Saree",
    price: 5800,
    category: "ethnic",
    subcategory: "saree",
    sizes: ["Free Size"],
    colors: ["Red", "Gold", "Black"],
    tags: ["new", "trending"],
    description: "Hand-painted Madhubani art on pure cotton saree. Each piece is a unique artwork.",
    fabric: "Pure Cotton",
    occasion: "Cultural Event",
    inStock: true,
    rating: 4.9,
    reviewCount: 56,
    cssColor: "#D32F2F",
    patternType: "printed",
  },
  {
    id: "eth-008",
    name: "Embroidered Palazzo Set",
    price: 3100,
    originalPrice: 3800,
    category: "ethnic",
    subcategory: "suit",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Teal", "Pink", "White"],
    tags: ["sale"],
    description: "Stylish palazzo set with intricate thread embroidery on the kurta. Comfort meets elegance.",
    fabric: "Rayon",
    occasion: "Party",
    inStock: true,
    rating: 4.5,
    reviewCount: 167,
    cssColor: "#00695C",
    patternType: "embroidered",
  },
  {
    id: "eth-009",
    name: "Heavy Silk Sharara",
    price: 14500,
    category: "ethnic",
    subcategory: "suit",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pink", "Gold", "Blue"],
    tags: ["new", "bestseller"],
    description: "Royal heavy silk sharara with zardozi work. An heirloom piece for grand occasions.",
    fabric: "Heavy Silk",
    occasion: "Wedding",
    inStock: true,
    rating: 4.8,
    reviewCount: 34,
    cssColor: "#E91E63",
    patternType: "embroidered",
  },
  {
    id: "eth-010",
    name: "Block Print Kota Saree",
    price: 3900,
    category: "ethnic",
    subcategory: "saree",
    sizes: ["Free Size"],
    colors: ["Blue", "Green", "Orange"],
    tags: ["trending"],
    description: "Traditional Kota Doria saree with natural block print. Light as air, perfect for summers.",
    fabric: "Kota Doria",
    occasion: "Casual",
    inStock: true,
    rating: 4.6,
    reviewCount: 94,
    cssColor: "#1565C0",
    patternType: "printed",
  },
  // ─── WESTERN WEAR ───────────────────────────────────────────────
  {
    id: "wes-001",
    name: "Floral Midi Dress",
    price: 2800,
    originalPrice: 3500,
    category: "western",
    subcategory: "dress",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Pink", "Blue"],
    tags: ["trending", "new"],
    description: "Elegant floral midi dress with puff sleeves. Perfect for brunch, garden parties or office.",
    fabric: "Chiffon",
    occasion: "Party",
    inStock: true,
    rating: 4.5,
    reviewCount: 189,
    cssColor: "#FCE4EC",
    patternType: "printed",
  },
  {
    id: "wes-002",
    name: "Structured Blazer Set",
    price: 4800,
    category: "western",
    subcategory: "blazer",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Cream"],
    tags: ["new", "trending"],
    description: "Power-dressing structured blazer with matching trousers. Boss-girl energy guaranteed.",
    fabric: "Polyester Blend",
    occasion: "Office",
    inStock: true,
    rating: 4.7,
    reviewCount: 143,
    cssColor: "#212121",
    patternType: "solid",
  },
  {
    id: "wes-003",
    name: "Denim Wide-Leg Jeans",
    price: 1900,
    category: "western",
    subcategory: "jeans",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "Black", "White"],
    tags: ["bestseller"],
    description: "Trendy wide-leg denim jeans with a high-rise fit. Comfort all day, style all night.",
    fabric: "Denim",
    occasion: "Casual",
    inStock: true,
    rating: 4.6,
    reviewCount: 421,
    cssColor: "#1565C0",
    patternType: "solid",
  },
  {
    id: "wes-004",
    name: "Linen Co-ord Set",
    price: 3200,
    originalPrice: 3900,
    category: "western",
    subcategory: "coord-set",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Beige", "White", "Sage Green"],
    tags: ["new", "sale"],
    description: "Breathable linen co-ord set — cropped blazer with wide-leg trousers. Summer must-have.",
    fabric: "Linen",
    occasion: "Casual",
    inStock: true,
    rating: 4.7,
    reviewCount: 267,
    cssColor: "#D7CCC8",
    patternType: "solid",
  },
  {
    id: "wes-005",
    name: "Sequin Evening Gown",
    price: 7800,
    category: "western",
    subcategory: "gown",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Gold", "Black", "Silver"],
    tags: ["trending", "new"],
    description: "Show-stopping sequin gown for cocktail parties and formal events. All eyes on you.",
    fabric: "Net with Sequins",
    occasion: "Party",
    inStock: true,
    rating: 4.8,
    reviewCount: 72,
    cssColor: "#C9A96E",
    patternType: "sequined",
  },
  {
    id: "wes-006",
    name: "Crop Top & Skirt Set",
    price: 1600,
    category: "western",
    subcategory: "coord-set",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Red", "Black", "White", "Pink"],
    tags: ["bestseller", "trending"],
    description: "Cute crop top paired with a flared mini skirt. Perfect for college and casual outings.",
    fabric: "Cotton Blend",
    occasion: "Casual",
    inStock: true,
    rating: 4.4,
    reviewCount: 534,
    cssColor: "#C62828",
    patternType: "solid",
  },
  {
    id: "wes-007",
    name: "Maxi Boho Dress",
    price: 2400,
    originalPrice: 3000,
    category: "western",
    subcategory: "dress",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Brown", "Green"],
    tags: ["sale"],
    description: "Free-flowing boho maxi dress with geometric prints. Beach-to-city versatile style.",
    fabric: "Rayon",
    occasion: "Casual",
    inStock: true,
    rating: 4.5,
    reviewCount: 198,
    cssColor: "#4527A0",
    patternType: "printed",
  },
  {
    id: "wes-008",
    name: "Satin Slip Dress",
    price: 3400,
    category: "western",
    subcategory: "dress",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Gold", "Black", "Pink"],
    tags: ["new", "trending"],
    description: "Luxurious satin slip dress with adjustable straps. Effortlessly chic for evening wear.",
    fabric: "Satin",
    occasion: "Party",
    inStock: true,
    rating: 4.6,
    reviewCount: 88,
    cssColor: "#F8BBD9",
    patternType: "solid",
  },
  // ─── BRIDAL COLLECTION ───────────────────────────────────────────────
  {
    id: "bri-001",
    name: "Royal Bridal Lehenga",
    price: 45000,
    originalPrice: 55000,
    category: "bridal",
    subcategory: "lehenga",
    sizes: ["XS", "S", "M", "L", "Custom"],
    colors: ["Red", "Maroon", "Gold"],
    tags: ["bestseller", "new"],
    description: "The ultimate bridal lehenga — pure silk with hand-done zardozi embroidery in gold thread. Every bride's dream. Custom stitching available.",
    fabric: "Pure Silk with Zardozi",
    occasion: "Wedding",
    inStock: true,
    rating: 5.0,
    reviewCount: 47,
    cssColor: "#7B1A1A",
    patternType: "embroidered",
  },
  {
    id: "bri-002",
    name: "Pastel Bridal Saree",
    price: 28000,
    category: "bridal",
    subcategory: "saree",
    sizes: ["Free Size"],
    colors: ["Pink", "Peach", "Lavender"],
    tags: ["trending", "new"],
    description: "Soft pastel silk saree with delicate pearl and crystal embellishment. Perfect for the modern bride who wants something different.",
    fabric: "Georgette Silk",
    occasion: "Wedding",
    inStock: true,
    rating: 4.9,
    reviewCount: 29,
    cssColor: "#F8BBD9",
    patternType: "embroidered",
  },
  {
    id: "bri-003",
    name: "Bridal Sharara Set",
    price: 32000,
    originalPrice: 38000,
    category: "bridal",
    subcategory: "sharara",
    sizes: ["S", "M", "L", "XL", "Custom"],
    colors: ["Gold", "Ivory", "Pink"],
    tags: ["bestseller", "sale"],
    description: "Statement bridal sharara with heavy kundan and mirror work. Comes with dupatta and blouse.",
    fabric: "Heavy Crepe",
    occasion: "Wedding",
    inStock: true,
    rating: 4.9,
    reviewCount: 61,
    cssColor: "#E8C98A",
    patternType: "sequined",
  },
  {
    id: "bri-004",
    name: "Anarkali Bridal Gown",
    price: 22500,
    category: "bridal",
    subcategory: "anarkali",
    sizes: ["XS", "S", "M", "L", "Custom"],
    colors: ["Maroon", "Navy", "Teal"],
    tags: ["new"],
    description: "Floor-length bridal Anarkali with heavy embroidery and trail. Regal and timeless.",
    fabric: "Velvet with Net",
    occasion: "Wedding",
    inStock: true,
    rating: 4.8,
    reviewCount: 38,
    cssColor: "#880E4F",
    patternType: "embroidered",
  },
  {
    id: "bri-005",
    name: "Mehendi Ceremony Lehenga",
    price: 8500,
    originalPrice: 11000,
    category: "bridal",
    subcategory: "lehenga",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Yellow", "Green", "Orange"],
    tags: ["trending", "sale"],
    description: "Cheerful yellow-green lehenga specially designed for Mehendi celebrations. Block print with gota patti work.",
    fabric: "Georgette",
    occasion: "Mehendi",
    inStock: true,
    rating: 4.7,
    reviewCount: 83,
    cssColor: "#F9A825",
    patternType: "printed",
  },
  // ─── FUSION WEAR ───────────────────────────────────────────────
  {
    id: "fus-001",
    name: "Dhoti Pants Kurta Set",
    price: 3800,
    category: "fusion",
    subcategory: "kurta",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Beige"],
    tags: ["trending", "new"],
    description: "Modern dhoti pants paired with an asymmetric kurta. East meets West in perfect harmony.",
    fabric: "Linen Cotton",
    occasion: "Party",
    inStock: true,
    rating: 4.6,
    reviewCount: 142,
    cssColor: "#FAFAFA",
    patternType: "solid",
  },
  {
    id: "fus-002",
    name: "Printed Cape with Jeans",
    price: 2600,
    category: "fusion",
    subcategory: "cape",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Red", "Gold"],
    tags: ["new", "trending"],
    description: "Bandhani print cape top paired perfectly with jeans. Fusion fashion at its finest.",
    fabric: "Georgette",
    occasion: "Casual",
    inStock: true,
    rating: 4.5,
    reviewCount: 176,
    cssColor: "#0D47A1",
    patternType: "printed",
  },
  {
    id: "fus-003",
    name: "Jacket Lehenga",
    price: 9800,
    originalPrice: 12000,
    category: "fusion",
    subcategory: "lehenga",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Gold", "Ivory"],
    tags: ["bestseller", "sale"],
    description: "Trendy lehenga with a structured jacket top instead of traditional blouse. Party-ready fusion.",
    fabric: "Crepe Silk",
    occasion: "Party",
    inStock: true,
    rating: 4.8,
    reviewCount: 97,
    cssColor: "#1A1A1A",
    patternType: "embroidered",
  },
  {
    id: "fus-004",
    name: "Indo-Western Gown",
    price: 6200,
    category: "fusion",
    subcategory: "gown",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Green", "Blue", "Pink"],
    tags: ["new"],
    description: "Floor-length Indo-Western gown with ethnic print and western silhouette. Best of both worlds.",
    fabric: "Chiffon",
    occasion: "Cocktail",
    inStock: true,
    rating: 4.6,
    reviewCount: 58,
    cssColor: "#2E7D32",
    patternType: "printed",
  },
  {
    id: "fus-005",
    name: "Crop Blouse Palazzo Set",
    price: 2900,
    originalPrice: 3500,
    category: "fusion",
    subcategory: "suit",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Red", "Pink", "White"],
    tags: ["trending", "sale"],
    description: "Modern crop blouse with wide-leg palazzo — fusion silhouette that works for weddings and parties.",
    fabric: "Georgette",
    occasion: "Party",
    inStock: true,
    rating: 4.5,
    reviewCount: 211,
    cssColor: "#B71C1C",
    patternType: "embroidered",
  },
  {
    id: "fus-006",
    name: "Saree with Belt",
    price: 5400,
    category: "fusion",
    subcategory: "saree",
    sizes: ["Free Size"],
    colors: ["Gold", "Black", "Pink"],
    tags: ["trending", "new"],
    description: "Contemporary saree styling with a statement belt. Instagram-worthy look for millennials.",
    fabric: "Crepe",
    occasion: "Party",
    inStock: true,
    rating: 4.7,
    reviewCount: 134,
    cssColor: "#880E4F",
    patternType: "sequined",
  },
  {
    id: "fus-007",
    name: "Bandhani Kurti with Pants",
    price: 1900,
    category: "fusion",
    subcategory: "kurti",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Red", "Blue", "Yellow"],
    tags: ["bestseller"],
    description: "Tie-dye Bandhani kurti with straight pants. Traditional craft, modern cut.",
    fabric: "Cotton Silk",
    occasion: "Casual",
    inStock: true,
    rating: 4.5,
    reviewCount: 298,
    cssColor: "#D32F2F",
    patternType: "printed",
  },
  {
    id: "fus-008",
    name: "High-Low Kurta Skirt",
    price: 3300,
    category: "fusion",
    subcategory: "kurta",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Peach", "Green", "White"],
    tags: ["new"],
    description: "High-low hemline kurta paired with a flared skirt. Contemporary take on traditional dressing.",
    fabric: "Muslin",
    occasion: "Office",
    inStock: true,
    rating: 4.4,
    reviewCount: 86,
    cssColor: "#FFCCBC",
    patternType: "printed",
  },
]

export function getAllProducts(): Product[] {
  return products
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: Product["category"]): Product[] {
  return products.filter((p) => p.category === category)
}

export function getSimilarProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit)
}

export const FABRICS = [...new Set(products.map((p) => p.fabric))]
export const OCCASIONS = [...new Set(products.map((p) => p.occasion))]
export const ALL_COLORS = [...new Set(products.flatMap((p) => p.colors))]
